Upcoming events
Cesurhan/toc_monkeys pull request #21
Opened 2017-03-28 10:28 UTC by Awadje

Create upcoming events page for review

2017-03-28 13:51 UTC, miriamtocino requested changes
First of all, this pull is doing too much. I thought it was only about adding a partial that will render upcoming events in the public homepage. 

Does that make sense?

Please let me know and then I can check again 😄

2017-03-28 14:46 UTC, Tenicia reviewed
Michael
As said the HTMLcode,/tags should refer to ' bootstrap'.

2017-03-28 15:38 UTC, miriamtocino requested changes
Good progress! 💪 

Some small comments. 
Let me know when I can check again 😄

2017-03-28 15:38 UTC, miriamtocino commented on app/controllers/events_controller.rb
> +end
Why do you need this in this pull request?

2017-03-28 15:38 UTC, miriamtocino commented on app/models/event.rb
> +
Please remove these extra lines 😄

2017-03-28 15:38 UTC, miriamtocino commented on app/views/shared/_upcomingevents.html.erb
> +</html>
I would rename this file into `_upcoming_events.html.erb`.

Also be aware that it's a partial, so the only content that you need to add in there is this:

```html
<h1>
  Upcoming Events!
</h1>

<div class="row">
  <% @events.each do |event| %>
    <div class="col-md-4">
      <div class="card-block">
        <img src="https://www.codaisseur.com/assets/rocket-0e991969b204c33b21331483b1f7d49499fd3ddb507ae46d6d22a658a7a3b852.png" height=50/>
        <h3 class="card-title"><%= event.title %></h3>
        <p class="card-text"><%= event.location %></p>

        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  <% end %>
</div>
```

2017-03-28 15:38 UTC, miriamtocino commented on app/views/shared/_upcomingevents.html.erb
> +            <img src="https://www.codaisseur.com/assets/rocket-0e991969b204c33b21331483b1f7d49499fd3ddb507ae46d6d22a658a7a3b852.png" height=50/>
We learnt other ways to add an image to your projects, instead of taking them from the internet...
Do you remember? 😄

2017-03-28 15:38 UTC, miriamtocino commented on db/schema.rb
>  end
Did you make any changes to your database in this pull? 
I don't see any migration file, so please remove these changes from this pull 😄

2017-03-28 15:50 UTC, Awadje commented on app/controllers/events_controller.rb
> +end
I'm not sure why it's still in there I wanted the whole file removed for this pull. Must be the git issues will fix. It was in there by mistake.

2017-03-28 15:51 UTC, Awadje commented on app/models/event.rb
> +
Will do

2017-03-28 15:55 UTC, Awadje commented on app/views/shared/_upcomingevents.html.erb
> +            <img src="https://www.codaisseur.com/assets/rocket-0e991969b204c33b21331483b1f7d49499fd3ddb507ae46d6d22a658a7a3b852.png" height=50/>
Yes was being lazy..

2017-03-31 09:30 UTC, arnoFleming requested changes

2017-03-31 09:30 UTC, arnoFleming commented on spec/views/shared/_upcoming_events.html.erb_spec.rb
> +require 'rails_helper'
don't do this twice

2017-03-31 09:30 UTC, arnoFleming commented on spec/views/shared/_upcoming_events.html.erb_spec.rb
> +    it "renders event" do
move this into the other describe  block

2017-03-31 09:30 UTC, arnoFleming commented on db/seeds.rb
> +event1 = Event.create!(title: "TOC 1", image: "Image 1", location: "Amsterdam", spaces_available: 1, workshop_id: 1, status: true, sponsor_id: 1)
don't use `workshop_id: 1`

Create workshop, and assign them to a variable:
but use Rails' magic: `workshop: workshop_1`

Or like this: 
`workshop: Workshop.first`

2017-03-31 09:30 UTC, arnoFleming commented on db/schema.rb
> +
don't edit this file by hand

2017-04-02 21:33 UTC, closed without merging